baseURL = 'https://n8felton.com/technotes'
languageCode = 'en-us'
title = 'Technical notes by n8felton'
theme = "geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true